### ISSUE TITLE
azurerm_role_definition module unable to create role consistently

### ISSUE THREAD

**Issue by mrickly** [terraform-providers/terraform-provider-azurerm#10434]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

* terraform version 0.14.2

* azurerm version 2.44.0

### Affected Resource(s)

* `azurerm_role_definition`

### Terraform Configuration Files

```hcl
resource "azurerm_role_definition" "key_rotation_role" {
  name = "key-rotation-role"
  scope = var.scope
  description = "Custom role for the function apps of the SPAs that need permissions to perform key rotation"

  permissions {
    actions = [
      "Microsoft.ApiManagement/service/read",
      "Microsoft.ApiManagement/service/subscriptions/regeneratePrimaryKey/action",
      "Microsoft.ApiManagement/service/subscriptions/regenerateSecondaryKey/action",
      "Microsoft.ApiManagement/service/subscriptions/listSecrets/action"
    ]

    not_actions = []
  }

  assignable_scopes = [
    var.scope,
  ]
}
```

### Expected Behaviour

The role should be created in the azure api management service. The role should exist in the terraform state and be consistent with the role created in azure. 

### Actual Behaviour

In general, the first or the second GET request from the module on the created role resource fails with a 404. The role exists in Azure, but is removed from the terraform state. 

### Important Factoids
* The scope of the role is the api management service, not the subscription. 
* It seems not to matter whether we try to create one or more roles. 
* The create response from Azure looks like it contains the needed information. It it not clear to me why the GET requests from the module are necessary. In rare cases, both GET requests return 200 OK and the build proceeds with our role assignments.  
* It looks like the create operation (PUT) is asynchronous, leading to eventual consistency, but showing potentially inconsistent results when several GET requests are performed shortly after the resource was successfully created (HTTP 201).

### References

*

**Comment by mrickly** [comment]
@TomGeske: FYI

**Comment by tombuildsstuff** [comment]
hi @mrickly 

Thanks for opening this issue.

Taking a look through here, the root cause of this appears to be is the same as #440, where the Azure API creates a new Role Definition behind the scenes during updates then reconciles them a few seconds later - which is being fixed in #9850 - rather than having multiple issues (with the same root cause) open tracking the same thing, I'm going to close this issue in favour of #440 - would you mind subscribing to that issue?

Thanks!

**Comment by mrickly** [comment]
hi @tombuildsstuff : Thank you for your quick response. I gave a look at #440 and it does not look like the same problem to me. But maybe #9850 will solve it nonetheless. I will definitely try out the version containing the fix.

**Comment by tombuildsstuff** [comment]
@mrickly it's a different issue, but I believe the root cause is the same nonetheless - if the fix doesn't work for you when it becomes available please let us know and we'll take another look :)

**Comment by gettek** [comment]
Unfortunately still getting this in version 2.46.1, as mentioned in the related issue #10479

**Comment by tombuildsstuff** [comment]
@gettek #440 hasn't been fixed yet, so unfortunately this would remain an issue until that's resolved - as mentioned above please subscribe to #440 for updates.
