### ISSUE TITLE
Storage Soft Delete Support

### ISSUE THREAD

**Issue by rohrerb** [terraform-providers/terraform-provider-azurerm#1070]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Hello,

Could we get support for Storage Soft Delete?

Seperate PR requested to add support on the Azure Go SDK - https://github.com/Azure/azure-sdk-for-go/issues/1504

https://azure.microsoft.com/en-us/blog/soft-delete-for-azure-storage-blobs-now-in-public-preview/
https://docs.microsoft.com/en-us/azure/storage/blobs/storage-blob-soft-delete

Thank you.

**Comment by mcwumbly** [comment]
Just inlining some info after following this link above

> Separate PR requested to add support on the Azure Go SDK - Azure/azure-sdk-for-go#1504

That issue was closed with:

> The storage package in this repo is in maintenance mode, it's been replaced by the azblob package. I've ported this issue to its repo, see Azure/azure-storage-blob-go#37

And _that_ issue was closed with:

> This is supported in the 2018-03-28 service API version.

Where does that leave things here?

**Comment by genevieve** [comment]
@tombuildsstuff Would you mind if we PR this functionality?

**Comment by tombuildsstuff** [comment]
@mcwumbly 

> The storage package in this repo is in maintenance mode, it's been replaced by the azblob package. I've ported this issue to its repo, see Azure/azure-storage-blob-go#37

Unfortunately we're unable to adopt the replacement library at the current time due to the way it does error handling ([which is being tracked here](https://github.com/Azure/azure-storage-blob-go/issues/59))

@genevieve 

> @tombuildsstuff Would you mind if we PR this functionality?

Not at all, that'd be great if you wouldn't mind - however based on the comments above this would require either updates to the new Storage SDK (to remove the panic's) or the old one (to add this functionality). I've reached out to Microsoft about their suggestion here, given they own both of these SDK's.

Thanks!

**Comment by LW81** [comment]
Hi,
is there any update to this ?
We just identified one use-case where soft-delete would be of help for us, so it would be great if we can configure it via terraform directly.

Steffen

**Comment by geertn** [comment]
FYI, according to the issue referenced above (as blocker for implementing soft delete) the panic on DecodeString is fixed.

**Comment by tombuildsstuff** [comment]
@geertn that's true - however there's several other blocking issues preventing us from adopting that SDK at this time unfortunately: https://github.com/Azure/azure-storage-blob-go/issues/86 and https://github.com/Azure/azure-storage-blob-go/issues/47

**Comment by landro** [comment]
@tombuildsstuff , did you see the updates on https://github.com/Azure/azure-storage-blob-go/issues/86 and https://github.com/Azure/azure-storage-blob-go/issues/47 ? Does this basically mean that support for soft delete can be implemented in the provider in a 1-3 months timeframe?

**Comment by tombuildsstuff** [comment]
@landro I did - unfortunately that SDK still isn't usable for us, since it (in the case of #86) only supports a single API version and thus we can't guarantee it will work in Azure Regions other than Azure Public (which may not have the latest API Version, e.g. Azure Stack, which we require for [the Azure Backend](https://www.terraform.io/docs/backends/types/azurerm.html)).

We've recently determined that in order to ship 2.0 (#2807) we're going to need to upgrade the Storage SDK to a version which also supports context; as such we've recently started prototyping our own Storage SDK (which uses [Azure/go-autorest](https://github.com/Azure/go-autorest) under the hood, so is fully compatible [with the existing Azure SDK for Go](https://github.com/Azure/azure-sdk-for-go).

Whilst this is an approach we were hoping to avoid (insofar as we'd rather use the official SDK than maintain our own) - this appears to be the most pragmatic approach to deliver these features, and 2.0 in general for the moment.

Thanks!

**Comment by stuartleeks** [comment]
I was just searching for this issue to start a conversation about whether the implementation for this should be a new resource (e.g. `azurerm_storage_service_properties`) or be created as a property on the existing `azurerm_storage_account` when I noticed that @benjamin37 has already created a PR!

The [API reference](https://docs.microsoft.com/en-us/rest/api/storageservices/get-blob-service-properties) show Get/Set calls but no delete - not sure whether that would cause an issue if it were created as a separate resource (which feels a bit cleaner to me)?

Also, in terms of shape, I was thinking something like

```terraform
resource "azurerm_storage_service_properties" "test" {
  storage_account_id = "/subscriptions/..."
  delete_retention_policy = {
    enabled = true
    days = 10
  }
}
```

That way this could be generalised to the other properties that are supported, e.g. 

```terraform
resource "azurerm_storage_service_properties" "test" {
  storage_account_id = "/subscriptions/..."
  delete_retention_policy = {
    enabled = true
    days = 10
  }
  cors = {
    allowed_origins = "example.com,test.example.com"
    allowed_methods = "GET,PUT"
    max_age_in_seconds = 3600
    ...
  }
  static_website {
    enabled = true
    index_document = "index.html"
    error_document_404 = "notfound.html"
  }
}
```

The Get/Set API allows you to set a group of properties (e.g. `cors` or `static_website`), so preserving that grouping in Terraform should simplify usage and implementation.

@tombuildsstuff / @katbyte - would love to get your thoughts on this. I.e. Should this be nested in the storage account vs a separate resource (noting that there is no delete API)? And does the resource shape above seem reasonable?

**Comment by landro** [comment]
Any news regarding storage account soft delete support, @tombuildsstuff ?
