### ISSUE TITLE
Intermittent failure updating `sku_name` or `max_size_gb` on failover group secondary db

### ISSUE THREAD

**Issue by erniebilling** [terraform-providers/terraform-provider-azurerm#11282]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

terraform 0.12.26
terraform-provider-azurerm_v2.55

### Affected Resource(s)

* `azurerm_mssql_database`
* `azurerm_sql_failover_group`

### Terraform Configuration Files

```hcl
variable instance_name { 
    type = string
    default = "test-mssql-db" 
}
variable resource_group { 
    type = string
    default = "test-mssql-fog-rg" 
}
variable db_name { 
    type = string
    default = "test-db"
}
variable labels { 
    type = map
    default = {} 
}
variable sku_name { 
    type = string 
    default = "GP_Gen5_2"
}
variable max_storage_gb { 
    type = number 
    default = 10
}

variable primary_server_name {
    type = string
    default = "test-mssql-db-primary"
}

variable secondary_server_name {
    type = string
    default = "test-mssql-db-secondary"
}

variable short_term_retention_days {
    type = number
    default = 7
}

provider "azurerm" {
  version = ">= 2.53.0"
  features {}
}

data "azurerm_sql_server" "primary_azure_sql_db_server" {
    name = var.primary_server_name
    resource_group_name          = var.resource_group
}

data "azurerm_sql_server" "secondary_sql_db_server" {
    name = var.secondary_server_name
    resource_group_name = var.resource_group
}

resource "azurerm_mssql_database" "primary_db" {
  name                = var.db_name
  server_id           = data.azurerm_sql_server.primary_azure_sql_db_server.id
  sku_name            = var.sku_name
  max_size_gb         = var.max_storage_gb
  tags                = var.labels
  short_term_retention_policy {
    retention_days = var.short_term_retention_days
  }
  count = 1
}

resource "azurerm_mssql_database" "secondary_db" {
  depends_on = [azurerm_mssql_database.primary_db[0]]
  name                = var.db_name
  server_id           = data.azurerm_sql_server.secondary_sql_db_server.id
  sku_name            = var.sku_name
  tags                = var.labels
  create_mode         = "Secondary"
  max_size_gb         = var.max_storage_gb
  creation_source_database_id  = azurerm_mssql_database.primary_db[0].id

  count = 1
}

resource "azurerm_sql_failover_group" "failover_group" {
  depends_on = [ azurerm_mssql_database.primary_db[0], azurerm_mssql_database.secondary_db[0] ]
  name                = var.instance_name
  resource_group_name = var.resource_group
  server_name         = data.azurerm_sql_server.primary_azure_sql_db_server.name
  databases           = [azurerm_mssql_database.primary_db[0].id]
  partner_servers {
    id = data.azurerm_sql_server.secondary_sql_db_server.id
  }

  read_write_endpoint_failover_policy {
    mode          = "Automatic"
    grace_minutes = 5
  }

  count = 1
}

output sqldbName {value = azurerm_mssql_database.primary_db[0].name}
output sqlServerName { value = azurerm_sql_failover_group.failover_group[0].name}
output sqlServerFullyQualifiedDomainName {value = format("%s.database.windows.net", azurerm_sql_failover_group.failover_group[0].name)}
output hostname {value = format("%s.database.windows.net", azurerm_sql_failover_group.failover_group[0].name)}
output port {value = 1433}
output name {value = azurerm_mssql_database.primary_db[0].name}
```

### Debug Output

https://gist.github.com/erniebilling/72b85f67c25d9a1c415cf2a89d26bb05

### Expected Behaviour

Secondary database sku and/or max size should successfully update

### Actual Behaviour

Occasionally fails with:
```
The operation cannot be performed since the database 'test_db' is in a replication relationship.
```

### Steps to Reproduce

1. Create primary and secondary mssql servers
2. `terraform apply -var 'primary_server_name=<primary servername> -var 'secondary_server_name=<secondary servername>`
Should successfully create databases and failover group

3. `terraform apply -var 'primary_server_name=<primary servername> -var 'secondary_server_name=<secondary servername> -var 'sku_name=GP_Gen5_8'`

Occasionally fails with above error. See log [gist](https://gist.github.com/erniebilling/72b85f67c25d9a1c415cf2a89d26bb05) for details.

### References

Opened per @aristosvo comment on https://github.com/cloudfoundry-incubator/csb-brokerpak-azure/issues/20

**Comment by aristosvo** [comment]
As [documented](https://docs.microsoft.com/en-us/azure/azure-sql/database/auto-failover-group-overview?tabs=azure-powershell#upgrading-or-downgrading-a-primary-database):

> When upgrading, we recommend that you upgrade all of the secondary databases first, and then upgrade the primary. When downgrading, reverse the order: downgrade the primary first, and then downgrade all of the secondary databases. When you upgrade or downgrade the database to a different service tier, this recommendation is enforced.
This sequence is recommended specifically to avoid the problem where the secondary at a lower SKU gets overloaded and must be re-seeded during an upgrade or downgrade process. You could also avoid the problem by making the primary read-only, at the expense of impacting all read-write workloads against the primary.

To support this pattern in Postgres we've implemented [this](https://github.com/terraform-providers/terraform-provider-azurerm/pull/10754), a similar approach for MSSQL can be taken.

I'll try to implement it during the weekend.

**Comment by aristosvo** [comment]
Actually, this is a different problem than I expected. The upgrade is failing on the secondary, and I expect (but am not 100% sure) that is not due to the order of upgrades, but due to changes introduced which shouldn't be done an a secondary. I've to look into the details for changes which are not allowed on a secondary and fix that.

**Comment by aristosvo** [comment]
The problem is more simple than expected, at least as far as I can see. I was only able to reproduce it when `max_storage_gb` was changed.

A secondary/failover database is not allowed to have a different `max_storage_gb` than its primary. When this value is changed for the primary, the secondary is scaled accordingly in the background. It seems the scaling is not concluded at the time the secondary is updated, which causes the error. The error is always reproducible by giving the secondary a different `max_storage_gb`.

@erniebilling Does your problem still occur when you remove `max_storage_gb` from the specification of your secondary?

**Comment by erniebilling** [comment]
@aristosvo Unfortunately, the problem still exists when I remove `max_storage_gb` from the specification for the secondary.

**Comment by aristosvo** [comment]
I'm sorry, I can't reproduce it consistently enough to diagnose the problem or detect a pattern.

How reproducible is it on your side? I've scaled 20x up and down and it occurred only once.., which makes it quit hard for me to do something about it.

**Comment by erniebilling** [comment]
@aristosvo About 50-50, but since its the same error as trying to update `max_storage_gb` it is likely the same root cause. Can you debug from that side?

**Comment by aristosvo** [comment]
It seems I can up the reproduction ratio by changing `max_storage_gb` at the same time. Can you reduce the error ratio by only changing SKU?

I believe this is a problem which is not related to Terraform, but due to the Azure API's. I'm not sure whether we can do something to mitigate it from the TF side.., I'll try some things, but I'm not very hopeful that it will result in a feasible solution.

**Comment by erniebilling** [comment]
I've collected log files for [success](https://gist.github.com/erniebilling/0b38f694cffab09b155420556a9a1771) and [failure](https://gist.github.com/erniebilling/1c68aae9435d5dc9869a6384a9226481)

Hopefully those may help.

**Comment by erniebilling** [comment]
Seems very timing related, hard to reproduce in higher latency situations. Is there some status that can be monitored to sequence or retry the operations?

**Comment by aristosvo** [comment]
The thing I want to try is to check SKU/size directly after changes in TF to make sure this is processed and see if that shows a pattern.

Other than that, I haven't found a status which indicates the service is not ready, but I'll take a second look.

**Comment by winnab** [comment]
@aristosvo Any updates on this issue?

**Comment by aristosvo** [comment]
@winnab Yes, review is done, I've to push a few fixes and retest. Probably released next cycle, but that depends on HC.

**Comment by aristosvo** [comment]
@katbyte this issue is still showing in low latency situations, can you please reopen?

**Comment by aristosvo** [comment]
@erniebilling I believe I've fixed it in #11401, but as I'm unable to reproduce it myself..

In my previous fix I've introduced a bug myself, but I believe the second fix improves the situation for low latency situations compared to the original situation by removing the option to set `max_size_gb` at all for secondaries, and also doesn't fill in the previous size (bug in my fix). I'll give up if this fix doesn't work for you.

**Comment by winnab** [comment]
Thanks very much for this, @aristosvo. Some folks on our team will take a look and see if this resolves the issue.
