### ISSUE TITLE
cannot create azurerm_managed_disk due to "The async operation failed."

### ISSUE THREAD

**Issue by rgl** [terraform-providers/terraform-provider-azurerm#6029]
### Terraform (and AzureRM Provider) Version

```
Terraform v0.12.23
+ provider.azurerm v2.0.0 (this also happens with v2.1.0)
+ provider.random v2.2.1
+ provider.template v2.1.2
```

### Affected Resource(s)

* `azurerm_managed_disk`

### Terraform Configuration Files

```hcl
terraform {
  required_version = ">= 0.12"
}

provider "azurerm" {
  version = "~> 2.0" # NB the problem described in this isse also happens with 2.1
  features {}
}

# NB you can test the relative speed from you browser to a location using https://azurespeedtest.azurewebsites.net/
# get the available locations with: az account list-locations --output table
variable "location" {
  default = "France Central" # see https://azure.microsoft.com/en-us/global-infrastructure/france/
}

# NB this name must be unique within the Azure subscription.
#    all the other names must be unique within this resource group.
variable "resource_group_name" {
  default = "rgl-ubuntu-vm-example"
}

resource "azurerm_resource_group" "example" {
  name     = var.resource_group_name # NB this name must be unique within the Azure subscription.
  location = var.location
}

resource "azurerm_managed_disk" "app_data" {
  name                 = "app_data"
  resource_group_name  = azurerm_resource_group.example.name
  location             = azurerm_resource_group.example.location
  create_option        = "Empty"
  disk_size_gb         = 10
  storage_account_type = "StandardSSD_LRS"
}
```

### Debug Output

```
2020-03-07T20:44:31.607Z [INFO]  plugin.terraform-provider-azurerm_v2.0.0_x5: [INFO] preparing arguments for Azure ARM Managed Disk creation.
2020-03-07T20:44:31.608Z [DEBUG] plugin.terraform-provider-azurerm_v2.0.0_x5: [DEBUG] AzureRM Request: 
2020-03-07T20:44:31.608Z [DEBUG] plugin.terraform-provider-azurerm_v2.0.0_x5: GET /subscriptions/5d1a30d6-67a4-40be-984e-6e427e255c7e/resourceGroups/rgl-ubuntu-vm-example/providers/Microsoft.Compute/disks/app_data?api-version=2019-07-01 HTTP/1.1
2020-03-07T20:44:31.608Z [DEBUG] plugin.terraform-provider-azurerm_v2.0.0_x5: Host: management.azure.com
2020-03-07T20:44:31.608Z [DEBUG] plugin.terraform-provider-azurerm_v2.0.0_x5: User-Agent: Go/go1.12.6 (amd64-linux) go-autorest/v13.3.0 Azure-SDK-For-Go/v38.1.0 compute/2019-07-01 HashiCorp Terraform/0.12.23 (+https://www.terraform.io) Terraform Plugin SDK/1.6.0 terraform-provider-azurerm/2.0.0 pid-222c6c49-1b0a-5959-a213-6608f9eb8820
2020-03-07T20:44:31.608Z [DEBUG] plugin.terraform-provider-azurerm_v2.0.0_x5: X-Ms-Correlation-Request-Id: f439accd-006e-b0bb-3ed7-faf35f14ac78
2020-03-07T20:44:31.608Z [DEBUG] plugin.terraform-provider-azurerm_v2.0.0_x5: Accept-Encoding: gzip
2020-03-07T20:44:31.608Z [DEBUG] plugin.terraform-provider-azurerm_v2.0.0_x5: 
2020-03-07T20:44:31.608Z [DEBUG] plugin.terraform-provider-azurerm_v2.0.0_x5: 
2020-03-07T20:44:31.919Z [DEBUG] plugin.terraform-provider-azurerm_v2.0.0_x5: [DEBUG] AzureRM Response for https://management.azure.com/subscriptions/5d1a30d6-67a4-40be-984e-6e427e255c7e/resourceGroups/rgl-ubuntu-vm-example/providers/Microsoft.Compute/disks/app_data?api-version=2019-07-01: 
2020-03-07T20:44:31.919Z [DEBUG] plugin.terraform-provider-azurerm_v2.0.0_x5: HTTP/2.0 404 Not Found
2020-03-07T20:44:31.919Z [DEBUG] plugin.terraform-provider-azurerm_v2.0.0_x5: Date: Sat, 07 Mar 2020 20:44:31 GMT
2020-03-07T20:44:31.919Z [DEBUG] plugin.terraform-provider-azurerm_v2.0.0_x5: Server: Microsoft-IIS/10.0
2020-03-07T20:44:31.919Z [DEBUG] plugin.terraform-provider-azurerm_v2.0.0_x5: Content-Length: 0
2020-03-07T20:44:31.919Z [DEBUG] plugin.terraform-provider-azurerm_v2.0.0_x5: 
2020-03-07T20:44:31.919Z [DEBUG] plugin.terraform-provider-azurerm_v2.0.0_x5: 
2020-03-07T20:44:31.920Z [DEBUG] plugin.terraform-provider-azurerm_v2.0.0_x5: [DEBUG] AzureRM Request: 
2020-03-07T20:44:31.920Z [DEBUG] plugin.terraform-provider-azurerm_v2.0.0_x5: PUT /subscriptions/5d1a30d6-67a4-40be-984e-6e427e255c7e/resourceGroups/rgl-ubuntu-vm-example/providers/Microsoft.Compute/disks/app_data?api-version=2019-07-01 HTTP/1.1
2020-03-07T20:44:31.920Z [DEBUG] plugin.terraform-provider-azurerm_v2.0.0_x5: Host: management.azure.com
2020-03-07T20:44:31.921Z [DEBUG] plugin.terraform-provider-azurerm_v2.0.0_x5: User-Agent: Go/go1.12.6 (amd64-linux) go-autorest/v13.3.0 Azure-SDK-For-Go/v38.1.0 compute/2019-07-01 HashiCorp Terraform/0.12.23 (+https://www.terraform.io) Terraform Plugin SDK/1.6.0 terraform-provider-azurerm/2.0.0 pid-222c6c49-1b0a-5959-a213-6608f9eb8820
2020-03-07T20:44:31.921Z [DEBUG] plugin.terraform-provider-azurerm_v2.0.0_x5: Content-Length: 198
2020-03-07T20:44:31.921Z [DEBUG] plugin.terraform-provider-azurerm_v2.0.0_x5: Content-Type: application/json; charset=utf-8
2020-03-07T20:44:31.921Z [DEBUG] plugin.terraform-provider-azurerm_v2.0.0_x5: X-Ms-Correlation-Request-Id: f439accd-006e-b0bb-3ed7-faf35f14ac78
2020-03-07T20:44:31.921Z [DEBUG] plugin.terraform-provider-azurerm_v2.0.0_x5: Accept-Encoding: gzip
2020-03-07T20:44:31.921Z [DEBUG] plugin.terraform-provider-azurerm_v2.0.0_x5: 
2020-03-07T20:44:31.921Z [DEBUG] plugin.terraform-provider-azurerm_v2.0.0_x5: {"location":"francecentral","properties":{"creationData":{"createOption":"Empty"},"diskSizeGB":10,"encryption":{"type":"EncryptionAtRestWithPlatformKey"}},"sku":{"name":"StandardSSD_LRS"},"tags":{}}
2020-03-07T20:44:31.947Z [DEBUG] plugin.terraform-provider-azurerm_v2.0.0_x5: [DEBUG] AzureRM Response for https://management.azure.com/subscriptions/5d1a30d6-67a4-40be-984e-6e427e255c7e/resourceGroups/rgl-ubuntu-vm-example/providers/Microsoft.Compute/disks/app_data?api-version=2019-07-01: 
2020-03-07T20:44:31.947Z [DEBUG] plugin.terraform-provider-azurerm_v2.0.0_x5: HTTP/2.0 404 Not Found
2020-03-07T20:44:31.947Z [DEBUG] plugin.terraform-provider-azurerm_v2.0.0_x5: Content-Length: 0
2020-03-07T20:44:31.947Z [DEBUG] plugin.terraform-provider-azurerm_v2.0.0_x5: Date: Sat, 07 Mar 2020 20:44:31 GMT
2020-03-07T20:44:31.947Z [DEBUG] plugin.terraform-provider-azurerm_v2.0.0_x5: Server: Microsoft-IIS/10.0
2020-03-07T20:44:31.947Z [DEBUG] plugin.terraform-provider-azurerm_v2.0.0_x5: 
2020-03-07T20:44:31.947Z [DEBUG] plugin.terraform-provider-azurerm_v2.0.0_x5: 
2020/03/07 20:44:31 [DEBUG] azurerm_managed_disk.app_data: apply errored, but we're indicating that via the Error pointer rather than returning it: Error creating/updating Managed Disk "app_data" (Resource Group "rgl-ubuntu-vm-example"): compute.DisksClient#CreateOrUpdate: Failure sending request: StatusCode=404 -- Original Error: Code="Failed" Message="The async operation failed."
2020/03/07 20:44:31 [TRACE] <root>: eval: *terraform.EvalMaybeTainted
2020/03/07 20:44:31 [TRACE] EvalMaybeTainted: azurerm_managed_disk.app_data encountered an error during creation, so it is now marked as tainted
2020/03/07 20:44:31 [TRACE] <root>: eval: *terraform.EvalWriteState
2020/03/07 20:44:31 [TRACE] EvalWriteState: removing state object for azurerm_managed_disk.app_data
2020/03/07 20:44:31 [TRACE] <root>: eval: *terraform.EvalApplyProvisioners
2020/03/07 20:44:31 [TRACE] EvalApplyProvisioners: azurerm_managed_disk.app_data has no state, so skipping provisioners
2020/03/07 20:44:31 [TRACE] <root>: eval: *terraform.EvalMaybeTainted
2020/03/07 20:44:31 [TRACE] EvalMaybeTainted: azurerm_managed_disk.app_data encountered an error during creation, so it is now marked as tainted
2020/03/07 20:44:31 [TRACE] <root>: eval: *terraform.EvalWriteState
2020/03/07 20:44:31 [TRACE] EvalWriteState: removing state object for azurerm_managed_disk.app_data
2020/03/07 20:44:31 [TRACE] <root>: eval: *terraform.EvalIf
2020/03/07 20:44:31 [TRACE] <root>: eval: *terraform.EvalIf
2020/03/07 20:44:31 [TRACE] <root>: eval: *terraform.EvalWriteDiff
2020/03/07 20:44:31 [TRACE] <root>: eval: *terraform.EvalApplyPost
2020/03/07 20:44:31 [ERROR] <root>: eval: *terraform.EvalApplyPost, err: Error creating/updating Managed Disk "app_data" (Resource Group "rgl-ubuntu-vm-example"): compute.DisksClient#CreateOrUpdate: Failure sending request: StatusCode=404 -- Original Error: Code="Failed" Message="The async operation failed."
2020/03/07 20:44:31 [ERROR] <root>: eval: *terraform.EvalSequence, err: Error creating/updating Managed Disk "app_data" (Resource Group "rgl-ubuntu-vm-example"): compute.DisksClient#CreateOrUpdate: Failure sending request: StatusCode=404 -- Original Error: Code="Failed" Message="The async operation failed."
```

### Expected Behavior

Be able to create a azurerm_managed_disk.

### Actual Behavior

```
azurerm_resource_group.example: Creating...
azurerm_resource_group.example: Creation complete after 2s [id=/subscriptions/5d1a30d6-67a4-40be-984e-6e427e255c7e/resourceGroups/rgl-ubuntu-vm-example]
azurerm_managed_disk.app_data: Creating...

Error: Error creating/updating Managed Disk "app_data" (Resource Group "rgl-ubuntu-vm-example"): compute.DisksClient#CreateOrUpdate: Failure sending request: StatusCode=404 -- Original Error: Code="Failed" Message="The async operation failed."

  on main.tf line 38, in resource "azurerm_managed_disk" "app_data":
  38: resource "azurerm_managed_disk" "app_data" {

```

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

* I'm using `az login` to login into a regular user account (using github authentication to login into azure).
* I'm using an Azure Pass subscription.
* Using `terraform apply` again still has the same problem.
* I can create the disk using the azure portal without problems.

**Comment by tombuildsstuff** [comment]
hi @rgl 

Thanks for opening this issue

Taking a look into this the error message being returned from the Azure API here (`The async operation failed`) is stating that this is an internal error provisioning this resource on Azure's side.

Since this is an internal error on Azure's side it's not possible for Terraform to know how to proceed automatically here (e.g. if Azure's having an outage, re-attempting would be result in the same error) - as such there's no means for us to automatically recover from this.

Instead you should be able to re-run `terraform plan` and `terraform apply` to confirm the updated changes and re-apply these, which should fix this - would you be able to take a look and see if that works for you? Since this is a temporary internal error within Azure (that should be fixed by re-running Terraform) I'm going to close this issue for the moment - but please let us know if that doesn't work for you and we'll take another look.

Thanks!

**Comment by rgl** [comment]
Like I said, running terraform several times does not fix the issue for me. Also, doing the same operation from the UI works fine.

Is there anything that I should try to troubleshoot this?

**Comment by rgl** [comment]
This still happens in v2.3.0 :-(
