### ISSUE TITLE
azurerm_kubernetes_cluster.default_node_pool.node_taints is unusable or its impossible to taint master node pool

### ISSUE THREAD

**Issue by Nek0trkstr** [terraform-providers/terraform-provider-azurerm#8031]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```
Terraform v0.12.29
+ provider.azuread v0.11.0
+ provider.azurerm v2.5.0
+ provider.random v2.3.0

azurerm=2.5.0
```

### Affected Resource(s)

* `azurerm_kubernetes_cluster`

### Terraform Configuration Files

```hcl
resource "azurerm_resource_group" "example" {
  name     = "example-resources"
  location = "West Europe"
}

resource "azurerm_kubernetes_cluster" "example" {
  name                = "example-aks1"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  dns_prefix          = "exampleaks1"

  default_node_pool {
    name       = "default"
    node_count = 1
    vm_size    = "Standard_D2_v2"
   node_taints = ["node-role.kubernetes.io/master=true:NoSchedule"] 
  }

  identity {
    type = "SystemAssigned"
  }
}

resource "azurerm_kubernetes_cluster_node_pool" "example" {
  name                  = "internal"
  kubernetes_cluster_id = azurerm_kubernetes_cluster.example.id
  vm_size               = "Standard_DS2_v2"
  node_count            = 1
}
```

### Debug Output

Dont think that debug output will help in anyway here

### Expected Behavior

Tainting a master node pool should be possible. 

### Actual Behavior

Applying plan produced from this config, you will get:
Error: creating Managed Kubernetes Cluster "*" (Resource Group "*"): containerservice.ManagedClustersClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="CanNotTaintAllAgentPools" Message="Operation failed due to insufficient nodes for system pod scheduling. Placing custom taints on all node pools is not supported. Retry the operation and leave at least one node pool untainted."

So what I've tried is to deploy cluster with worker pool without tainting masters. And after the deploy succeeded to add a taint on master node pool (now we will have at least 1 untained node pool), but:
Error: updating Default Node Pool "*" (Resource Group "*") containerservice.AgentPoolsClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="PropertyChangeNotAllowed" Message="Changing property 'properties.nodeTaints' is not allowed." Target="properties.nodeTaints"

### Steps to Reproduce

1. `terraform plan`
2. `terraform apply`

### Important Factoids

Running in Azure Germany

**Comment by tombuildsstuff** [comment]
hi @Nek0trkstr 

Thanks for opening this issue.

Taking a look into this this has been fixed in a newer version of the Azure Provider - we're currently on version v2.21.0 - which you can upgrade to by updating the version in the Provider block (as shown below) and then running `terraform init -upgrade`:

```
provider "azurerm" {
  version = "=2.21.0"
}
```

.. which should solve this for you - would you be able to take a look and see if that works for you? Since this should be fixed by updating to the latest version of the Azure Provider I'm going to close this issue for the moment but please let us know if that doesn't work for you and we'll take another look.

Thanks!

**Comment by Nek0trkstr** [comment]
Hi @tombuildsstuff 
Thank you for quick response.
As you suggested I have upgraded the azurerm provider to 2.21.0 and indeed I see that now changing a node_taint will force azurerm_kubernetes_cluster replacement which makes sense, cause modifying this value is not possible.

However when creating a new cluster I still get the following error:
```
containerservice.ManagedClustersClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="CanNotTaintAllAgentPools" Message="Operation failed due to insufficient nodes for system pod scheduling. Placing custom taints on all node pools is not supported. Retry the operation and leave at least one node pool untainted."
```
Which makes sense as well - I do not have a node pool when creating a new cluster.

So now the situation is: node_taint will not work on creation cause its the only nodepool available, and tainting nodepool after creating will force a replacement and the same error from creation will appear.
Is it an Azure limitation? Seems like node taints should be user responsibility and mechanism to disable such checks can help, or at least flag to set "node-role.kubernetes.io/master=true:NoSchedule" taint to prevent unnecessary pods from running on master nodes.

**Comment by tombuildsstuff** [comment]
@Nek0trkstr indeed, unfortunately this appears to be an Azure limitation in that these are setable at provisioning time only (presumably some these are configured using a VM Extension on each VM in the Node Pool, but I may be wrong).

Longer-term we'd like to have a means of supporting cycling the default node pool (and making these fields at least updateable) - but there's some larger questions on how to do that (e.g. do we provision a secondary temporary default node pool?) - and ultimately that won't fix this specific issue with the Node Taints being immutable.

In this instance I'm going to suggest [opening an issue with AKS](https://github.com/Azure/AKS/issues) however - since it feels like these should be updatable (and they should be able to confirm either way/if that's planned)
